is_train : True
dir_split : 'train'
# data_dir : '/mnt/DATA3/mishra/abhiram/KMIS/knowledge-aware-mmt/data/coco/' # coco
data_dir: 'data/cofar_brand' # cofar brand
max_seq_len : 120 # max words allowed in caption
max_vis_seq_len : 50 # max object features taken from images.
mask_probability : 0.15 # probability for a word to be masked, same as BERT
num_captions_per_img : 3
num_captions_per_img_val : 3
use_word_overlap : False  # only set to true when finetuning on WebQA and you want to choose hard -ves using word overlap.


use_cofar_knowledge : True